from abc import ABCMeta

from app.autogenerated.adapters import (
    can_change_velocity_adapter,
    consumes_fuel_adapter,
    movable_adapter,
    rotatable_adapter,
)
from app.core.command import ICommand
from app.core.ioc import IoC
from app.game.uobject import UObject


def ioc_setup_adapters() -> None:
    adapter_dict: dict[ABCMeta, type] = {
        can_change_velocity_adapter.ICanChangeVelocity: can_change_velocity_adapter.CanChangeVelocityAdapter,
        consumes_fuel_adapter.IConsumesFuel: consumes_fuel_adapter.ConsumesFuelAdapter,
        movable_adapter.IMovable: movable_adapter.MovableAdapter,
        rotatable_adapter.IRotatable: rotatable_adapter.RotatableAdapter,
    }

    def get_adapter(interface: ABCMeta, uobj: UObject) -> object:
        return adapter_dict[interface](uobj)

    IoC[ICommand].resolve(
        "IoC.Scope.Register",
        "Adapter",
        get_adapter,
    ).execute()
