import pytest

from app.autogenerated.adapters.consumes_fuel_adapter import ConsumesFuelAdapter
from app.core.command import CommandError
from app.game.behaviour.fuel import (
    BurnFuelCommand,
    CheckFuelCommand,
    ioc_setup_iconsumesfuel,
)
from app.game.uobject import UObject
from tests.mocks import MockUObject


@pytest.fixture(autouse=True)
def _ioc_setup() -> None:
    ioc_setup_iconsumesfuel()


def make_fuel_consumer_uobject(
    amount: int, consumption: int, uobj: UObject | None = None
) -> UObject:
    if not uobj:
        uobj = MockUObject()
    uobj.set_property("fuel_amount", amount)
    uobj.set_property("fuel_consumption", consumption)
    return uobj


def test_check_fuel() -> None:
    uobj = make_fuel_consumer_uobject(10, 5)
    CheckFuelCommand(ConsumesFuelAdapter(uobj)).execute()

    uobj = make_fuel_consumer_uobject(10, 11)
    with pytest.raises(CommandError):
        CheckFuelCommand(ConsumesFuelAdapter(uobj)).execute()


def test_burn_fuel() -> None:
    uobj = make_fuel_consumer_uobject(10, 5)
    consumer = ConsumesFuelAdapter(uobj)
    BurnFuelCommand(consumer).execute()
    assert consumer.get_amount() == 5
    BurnFuelCommand(consumer).execute()
    assert consumer.get_amount() == 0
